var CommentConstants = {
  RECEIVE_COMMENTS: "RECEIVE_COMMENTS",
  RECEIVE_COMMENT: "RECEIVE_COMMENT",
  REMOVE_COMMENT: "REMOVE_COMMENT",
  UPDATE_COMMENT: "UPDATE_COMMENT"
};

module.exports = CommentConstants;
