var TopicConstants = {
  RECEIVE_TOPICS: "RECEIVE_TOPICS",
  RECEIVE_TOPIC: "RECEIVE_TOPIC",
  REMOVE_TOPIC: "REMOVE_TOPIC",
  RECEIVE_QUESTION_TOPICS: "RECEIVE_QUESTION_TOPICS",
  RECEIVE_QUESTION_TOPIC: "RECEIVE_QUESTION_TOPIC"
};

module.exports = TopicConstants;
